backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://blog.calebjay.com
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    path: '{{slug}}/index',
    media_folder: '',
    public_folder: '',
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Category", name: "categories", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
